### ISSUE TITLE
Attribute mapping should show name of catalog/manifest/package

### ISSUE THREAD

**Issue by fuzzylogiq** [oucsaw/munkiwebadmin#4]
If you have multiple mappings for the same JSS attribute pointing to the same manifest element type it gets confusing as to which does which without opening them from the list view. Perhaps add the name of the manifest element to the end of the mapping in the list view.

**Comment by oucsaw** [comment]
Is the new view better (pushed out with the change to add an enable/disable flag to mappings) ?

**Comment by oucsaw** [comment]
Having talked (out of band) with @fuzzylogiq, the last commit  c591a85..5db4064 resolves this issue
